services:
  postgres:
    image: postgres:15-alpine
    container_name: jobboard-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jobboard
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: "./api"
    container_name: jobboard-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

volumes:
  postgres_data:
